sudo: false
language: node_js
node_js:
  - '6'
  - '7'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
env:
  global:
    # EGG_PASSPORT_BITBUCKET_CLIENT_ID
    - secure: "PHWPtRtxq/sMQ5POSEnnnZeHTdV1W1arR2W2LiA3q43/o7e+U9qlsnAh3Ua5rmQgkRQiieGncAwqOkCQd/h1uCqVd428tvizCHdP6e8CwtdNGxGB4SVFJBAQ129gb4A124h5wNLlB4bufsgwuKUpgGu04HuERuTVg+7GpNgN8WUwGkrM8ewlNniG5lL0IDmqFPYW51Wby2Dr72OTB0ySz9pH9um2Am3oUZ6XqXcPRiwODI89RepG+8PHhW8zTDCKNnc9zb28rinCearg2/jzk75Kg6va1OyHgnewsZIreI1jgyeOYzbBtr+ETDCtiukgmt5hQjL7KnTTh47X4MCWlKDBCOIWG73PDGnyqToZHjofqvQavc2hog/0CHCDvZdxAhJ8FAA2f9tjCmBAQTFVOjrypyOCB+MQVGasJyweJldHxyQmEHOSq6tFSLlFyQ/NW6lfNysue7P5OjpdEJmdj4n1VFOyAyJdvGzm9t9V1FWjvdpdgkqvfP/d0AsLVhdd0Ro9DT2JAdi29/4HT0CGYEXYJuJUJ33n3JdwzHmHTGKuvCJAF84lOuzGRkiu/X2i3Ufw4Qo/luRZfpU612xQ4eQXRVkYWB8Toud1x4OcJU9dVfzpBraj7DLWjtpydWS3bzTOApulfpDUnSsVKjR6FvHxAHNaogVaModIiP929VM="
    # EGG_PASSPORT_BITBUCKET_CLIENT_SECRET
    - secure: "WEG+5lcCB2Uw5CCpHBL50oUKG5V9WPthiusMYKu7SecSgoc2ongYqtPpAXMzCwUWOy+LTVa75yjPZhaCTAWOh1safSGX9NnobqwU9eQa1YrTaw0Vr+yD9wwmILQ9jL52rAVreAR+dw9JnK+m5ttv22UmdhMlaa2e6YeoXwu3QfspG5OqI0yFNGILtuArvElUVPXpt24gm3Xwh2kKjkHCJRRPoghDjpwmpyjh+vaMzN8ZfRdFrlj+OyRXDpPWHDO1XbDNX/bdmsZDeQrWvLBZFJ6Rj2OlIYuEx7MjrAPEfy8qkEg0AvLYVqPt1tCMkkAYfY65qC7pcbXtb1AozGY3sRoaFi+5EBv1FwBoND0E2+IeHFto0JVoEWq2echLMkNSyF9TOkDIHeS5KkDr/J8e5m6+91lTbiHwkfnSKaJ4oJL2iT8i56I7tZnUy4waaUg4nnfeGZFwUe4HWb+g6h2pCwoTPgMSyB+Sda++n2i4eYHahW1OsZenzQYScgBdr8b7W2yHyzirlZj61mXJcSTTO9rvRR4peY4Iqeh8hURL+7GJQ/3OCRMDje1r5aJcmaCoJHUBkto+VUGBf1kaCJx0oawx7p01IXgFKqH2vjCS8ZHKB94mGvGBS1YU+sIIG25enJ34HUkv3lK2rxPFzGLPzxWmlekeeBXcifYTWsnrrW8="
